### ISSUE TITLE
source gst in without .gs directory closes the shell

### ISSUE THREAD

**Issue by tonchis** [tonchis/gst#2]
Performing a `. gst in` in a directory without the `.gs` dir will source the `exit 1`, closing the current shell.

**Comment by pote** [comment]
Can confirm, I've been to lazy to fix this though. A simple check and meaningful error response should do the trick.

**Comment by tonchis** [comment]
Though it fixes the problem, it prints an ugly warning when using `gst in` for standalone commands.

``` bash
$ gst in
Directory .gs not found. Run `gst init` first.
/Users/tonchis/code/gst/bin/gst: line 46: return: can only `return' from a function or sourced script
```

Can we live with this?
