### ISSUE TITLE
`brew update` in README

### ISSUE THREAD

**Issue by weakish** [tonchis/gst#4]
> With Homebrew
> 
> ```
> brew tap tonchis/goodies && brew update && brew install gst
> ```

I think we just need tap & install.

**Comment by tonchis** [comment]
According to [brew-tap docs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md), tapping clones all repos in the tap, thus bringing the latest version, so `update` is not needed.

I'll update the docs!

Thanks @weakish
